version: "3.9"
services:
  postgres:
    build: ./postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  neo4j:
    build: ./neo4j
    image: "neo4j-server"
    ports:
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_log:/log
      - neo4j_conf:/conf

  redis:
    build: ./redis
    image: "redis-server"
    ports:
      - "6379:6379"

  goapp:
    build:
      context: ./goapp/
      dockerfile: Dockerfile
    depends_on:
      - "postgres"
      - "neo4j"
      - "redis"
    ports:
      - "8080:8080"

  nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    depends_on:
      - "goapp"
    ports:
      - "80:80"

volumes:
  postgres_data:
  neo4j_data:
  neo4j_log:
  neo4j_conf: