version: "3.9"
services:
  postgres:
    build: ./postgres
    ports:
      - "5432:5432"

  neo4j:
    build: ./neo4j
    image: "neo4j-server"
    ports:
      - "7687:7687"

  redis:
    build: ./redis
    image: "redis-server"
    ports:
      - "6379:6379"

  goapp:
    build:
      context: ./goapp/
      dockerfile: Dockerfile
    depends_on:
      - "postgres"
      - "neo4j"
      - "redis"
    ports:
      - "8080:8080"

  nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    depends_on:
      - "goapp"
    ports:
      - "80:80"